language: go

go:
  - 1.2
  - 1.3
  - tip

install: make updatedeps

script:
  - go test ./

before_script:
  - psql -c 'create database inappcloud_data_test;' -U postgres
  - psql -c 'create table posts (id serial, name text); create table comments (id serial, body text);' -d inappcloud_data_test -U postgres

env: DATABASE_URL=postgres://postgres@localhost/inappcloud_data_test

matrix:
  allow_failures:
    - go: tip
